### ISSUE TITLE
problems adding json files via terminal

### ISSUE THREAD

**Issue by chrispappas007** [ljmoser83/Toronto#1]
I've been able to connect to the repo remotely via terminal, and it appeared to initially have fetched the data successfully, but I can't actually get it to let me push any of my changes. And now, it does not appear to want to allow me to have any access to the repo. I can access and add the files via github desktop, and I am going to do so to move forward, but I will touch base with Rich to figure out what I've done in terminal that went so wrong.

**Comment by ljmoser83** [comment]
Understood. we will chat and find out how to deal with this shortly.
