### ISSUE TITLE
icon marker

### ISSUE THREAD

**Issue by chrispappas007** [ljmoser83/Toronto#8]
I've been unable to replace the standard leaflet marker with the one in the svg folder. I think I am either trying to change the marker in the wrong place or am using the wrong the method. I left the code commented out so you can see where I left off.

**Comment by ljmoser83** [comment]
I will dig into it this evening and see what I can do to help.

**Comment by rgdonohue** [comment]
I can have a look today as well.

**Comment by ljmoser83** [comment]
On another note, rich, I tried multiple methods to utilize the mapbox dark tilelayer and was unsuccessful. I defaulted back to the L.tilelayer method and slippy map you used in the lesson. It kept giving me an accessToken error. Have you ran into any issues with mapbox recently?

**Comment by rgdonohue** [comment]
@ljmoser83 Huh. And were you supplying the accessToken and using mapbox.js? If that's on a branch somewhere I can look.

**Comment by rgdonohue** [comment]
@chrispappas007 Have a look at what I did here: [b6a249e  ](https://github.com/ljmoser83/Toronto/commit/4497c8f0a93f46a5ee82ff9f2772dda4a90aa40d)?

You wanted that `pointToLayer` function for converting the feature to a marker:

```
        L.geoJson(cultSpot, {

            pointToLayer: function(feature, latlng) {
                return L.marker(latlng, {icon: cultIcon});
            },
         ....
```

**Comment by rgdonohue** [comment]
That SVG was also black, which wasn't showing up well on the dark background. It also had some SVG text in it which we don't want. I modified the SVG in Illustrator and tossed in an orange color.

Probably want to give add some attribute back into the file, in comments, pointed back to the author on the Noun project ...

**Comment by ljmoser83** [comment]
I have accepted the merge request and deem this issue resolved. closing issue.
